@base_url=http://localhost:3000

###
GET {{base_url}}/

###
GET {{base_url}}/employees

### 🍍
@id=random

GET {{base_url}}/employees/{{id}}


###
POST  {{base_url}}/employees
Content-Type: application/json

{
	"name": "Parhlep"
}
